# -*- coding: utf-8 -*-
"""FCM_2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u7cAeunRavK2OthW8ly6F3ndhC5KV_Zw
"""

import numpy as np

x = np.array([[1.],[2.],[3.]])
y = np.array([[2.],[3.],[4.]])
alpha = 0

for i in range(3):
  alpha = alpha + x[i]*y[i]


print(alpha)

def inner_product(x,y):
  n=len(x)
  alpha = 0
  for i in range(n):
    alpha = alpha + x[i]*y[i]
  return alpha

x = np.array([[1.],[2.],[3.]])
y = np.array([[2.],[3.],[4.]])
z = inner_product(x,y)




print(z)